STUDENT_NAME = "Ilya Sender"
STUDENT_GROUP = "IT-42"

DB_FILE = "workspace_ilya_sender.db"
APP_TITLE = "Notes Manager"

CASCADE_STEP = 40
DEFAULT_PREVIEW_LENGTH = 40

ORG_NAME = "KTBP"
LOG_FILE = "notes_manager.log"
LOG_MAX_BYTES = 1_000_000
LOG_BACKUP_COUNT = 3
RECENT_EXPORTS_MAX = 5
